// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 27acRQBdiDjAQuC2V3WuRn
// Component: __nHRIM-Ac
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import MyComponent from "../../MyComponent"; // plasmic-import: f-L2gtuvIT1/component

import { useScreenVariants as useScreenVariantsrpq5Sb9BmN8Qf } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: RPQ5SB9bmN8Qf/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_gap.module.css"; // plasmic-import: 27acRQBdiDjAQuC2V3WuRn/projectcss
import sty from "./PlasmicTeste.module.css"; // plasmic-import: __nHRIM-Ac/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: syO7ezynaxu/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: usT7wQdIWkk/icon

export type PlasmicTeste__VariantMembers = {};

export type PlasmicTeste__VariantsArgs = {};
type VariantPropType = keyof PlasmicTeste__VariantsArgs;
export const PlasmicTeste__VariantProps = new Array<VariantPropType>();

export type PlasmicTeste__ArgsType = {};
type ArgPropType = keyof PlasmicTeste__ArgsType;
export const PlasmicTeste__ArgProps = new Array<ArgPropType>();

export type PlasmicTeste__OverridesType = {
  root?: p.Flex<"div">;
  text?: p.Flex<"div">;
  myComponent?: p.Flex<typeof MyComponent>;
  svg?: p.Flex<"svg">;
};

export interface DefaultTesteProps {
  className?: string;
}

function PlasmicTeste__RenderFunc(props: {
  variants: PlasmicTeste__VariantsArgs;
  args: PlasmicTeste__ArgsType;
  overrides: PlasmicTeste__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsrpq5Sb9BmN8Qf()
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.text)}
      >
        {hasVariant(globalVariants, "screen", "mobile")
          ? "fdsfdsfdsfdsfome text"
          : "Enter some aaa text"}
      </div>

      <MyComponent
        data-plasmic-name={"myComponent"}
        data-plasmic-override={overrides.myComponent}
        className={classNames("__wab_instance", sty.myComponent)}
      />

      <svg
        data-plasmic-name={"svg"}
        data-plasmic-override={overrides.svg}
        className={classNames(projectcss.all, sty.svg)}
        role={"img"}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "text", "myComponent", "svg"],
  text: ["text"],
  myComponent: ["myComponent"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  text: "div";
  myComponent: typeof MyComponent;
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTeste__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTeste__VariantsArgs;
    args?: PlasmicTeste__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicTeste__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicTeste__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicTeste__ArgProps,
          internalVariantPropNames: PlasmicTeste__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicTeste__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTeste";
  } else {
    func.displayName = `PlasmicTeste.${nodeName}`;
  }
  return func;
}

export const PlasmicTeste = Object.assign(
  // Top-level PlasmicTeste renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    text: makeNodeComponent("text"),
    myComponent: makeNodeComponent("myComponent"),
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicTeste
    internalVariantProps: PlasmicTeste__VariantProps,
    internalArgProps: PlasmicTeste__ArgProps
  }
);

export default PlasmicTeste;
/* prettier-ignore-end */
