// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 27acRQBdiDjAQuC2V3WuRn
// Component: zQ4iO2yHK9
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_gap.module.css"; // plasmic-import: 27acRQBdiDjAQuC2V3WuRn/projectcss
import sty from "./PlasmicCmsDataLoader.module.css"; // plasmic-import: zQ4iO2yHK9/css

export type PlasmicCmsDataLoader__VariantMembers = {};

export type PlasmicCmsDataLoader__VariantsArgs = {};
type VariantPropType = keyof PlasmicCmsDataLoader__VariantsArgs;
export const PlasmicCmsDataLoader__VariantProps = new Array<VariantPropType>();

export type PlasmicCmsDataLoader__ArgsType = {};
type ArgPropType = keyof PlasmicCmsDataLoader__ArgsType;
export const PlasmicCmsDataLoader__ArgProps = new Array<ArgPropType>();

export type PlasmicCmsDataLoader__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultCmsDataLoaderProps {
  className?: string;
}

function PlasmicCmsDataLoader__RenderFunc(props: {
  variants: PlasmicCmsDataLoader__VariantsArgs;
  args: PlasmicCmsDataLoader__ArgsType;
  overrides: PlasmicCmsDataLoader__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root
      )}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCmsDataLoader__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCmsDataLoader__VariantsArgs;
    args?: PlasmicCmsDataLoader__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicCmsDataLoader__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicCmsDataLoader__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicCmsDataLoader__ArgProps,
          internalVariantPropNames: PlasmicCmsDataLoader__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicCmsDataLoader__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCmsDataLoader";
  } else {
    func.displayName = `PlasmicCmsDataLoader.${nodeName}`;
  }
  return func;
}

export const PlasmicCmsDataLoader = Object.assign(
  // Top-level PlasmicCmsDataLoader renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicCmsDataLoader
    internalVariantProps: PlasmicCmsDataLoader__VariantProps,
    internalArgProps: PlasmicCmsDataLoader__ArgProps
  }
);

export default PlasmicCmsDataLoader;
/* prettier-ignore-end */
