// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 27acRQBdiDjAQuC2V3WuRn
import * as React from "react";
import { CmsCredentialsProvider } from "@plasmicpkgs/plasmic-cms"; // plasmic-import: OREVbGCcgN/codeComponent
import { EmbedCss } from "@plasmicpkgs/plasmic-embed-css"; // plasmic-import: qF0uJxFztB/codeComponent
import { CommerceProviderComponent } from "@plasmicpkgs/commerce-shopify"; // plasmic-import: CSRQMDqlyz3-/codeComponent

export interface GlobalContextsProviderProps {
  children?: React.ReactElement;
  cmsCredentialsProviderProps?: Partial<
    Omit<React.ComponentProps<typeof CmsCredentialsProvider>, "children">
  >;
  embedCssProps?: Partial<
    Omit<React.ComponentProps<typeof EmbedCss>, "children">
  >;
  commerceProviderComponentProps?: Partial<
    Omit<React.ComponentProps<typeof CommerceProviderComponent>, "children">
  >;
}

export default function GlobalContextsProvider(
  props: GlobalContextsProviderProps
) {
  const {
    children,
    cmsCredentialsProviderProps,
    embedCssProps,
    commerceProviderComponentProps
  } = props;

  return (
    <CmsCredentialsProvider
      {...cmsCredentialsProviderProps}
      databaseId={
        cmsCredentialsProviderProps &&
        "databaseId" in cmsCredentialsProviderProps
          ? cmsCredentialsProviderProps.databaseId!
          : ("coe1tu8i5ew2Zb9Rdq8mwv" as const)
      }
      databaseToken={
        cmsCredentialsProviderProps &&
        "databaseToken" in cmsCredentialsProviderProps
          ? cmsCredentialsProviderProps.databaseToken!
          : ("amh3xspSffpsuRNbGpO1zsqeyq5q6TkTGaAxFzBYmzGxc2shT1CG8jQB4Ur0LHtKk9jcMxTvheZgoTDQ" as const)
      }
      host={
        cmsCredentialsProviderProps && "host" in cmsCredentialsProviderProps
          ? cmsCredentialsProviderProps.host!
          : ("https://studio.plasmic.app" as const)
      }
      locale={
        cmsCredentialsProviderProps && "locale" in cmsCredentialsProviderProps
          ? cmsCredentialsProviderProps.locale!
          : ("" as const)
      }
    >
      <EmbedCss
        {...embedCssProps}
        css={
          embedCssProps && "css" in embedCssProps
            ? embedCssProps.css!
            : ("/* CSS snippet */" as const)
        }
      >
        <CommerceProviderComponent
          {...commerceProviderComponentProps}
          accessToken={
            commerceProviderComponentProps &&
            "accessToken" in commerceProviderComponentProps
              ? commerceProviderComponentProps.accessToken!
              : ("ef7d41c7bf7e1c214074d0d3047bcd7b" as const)
          }
          storeDomain={
            commerceProviderComponentProps &&
            "storeDomain" in commerceProviderComponentProps
              ? commerceProviderComponentProps.storeDomain!
              : ("next-js-store.myshopify.com" as const)
          }
        >
          {children}
        </CommerceProviderComponent>
      </EmbedCss>
    </CmsCredentialsProvider>
  );
}
